# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

target 'RxTodoDemo' do
  use_frameworks!

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

end
